// src/components/TopToolbar.vue
<template>
  <div class="bg-white h-16 flex items-center justify-between sm:justify-start">
    <div class="flex items-center px-4">
      <button
        type="button"
        class="inline-flex items-center p-2 border border-transparent rounded-full shadow-sm text-gray-600 bg-transparent hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        @click="clearSelected"
      >
        <XIcon class="h-5 w-5" aria-hidden="true" />
      </button>
      <div class="mx-4">{{ numSelected }} selected</div>
    </div>
    <div class="px-4 sm:px-6 lg:px-8">
      <div class="py-3 flex justify-between">
        <div>
          <span class="relative z-0 inline-flex rounded-md space-x-3">
            <span class="hidden sm:inline-flex sm:shadow-sm">
              <tags-popover>
                <PopoverButton
                  type="button"
                  class="inline-flex -ml-px relative items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-blue-600 focus:border-blue-600"
                >
                  <ReplyIcon
                    class="mr-2.5 h-5 w-5 text-gray-400"
                    aria-hidden="true"
                  />
                  <span>Edit</span>
                </PopoverButton>
              </tags-popover>
            </span>

            <span class="inline-flex sm:hidden">
              <button
                type="button"
                class="inline-flex -ml-px relative items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-blue-600 focus:border-blue-600"
                @click="openTagsDialog"
              >
                <ReplyIcon
                  class="mr-2.5 h-5 w-5 text-gray-400"
                  aria-hidden="true"
                />
                <span>Edit</span>
                <tags-dialog ref="tagsDialog"></tags-dialog>
              </button>
            </span>

            <span class="inline-flex sm:shadow-sm">
              <button
                type="button"
                class="inline-flex -ml-px relative items-center px-4 py-2 rounded-md border border-gray-300 bg-white text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:outline-none focus:ring-1 focus:ring-blue-600 focus:border-blue-600"
                @click="openDeleteConfirmation"
              >
                <ArchiveIconSolid
                  class="mr-2.5 h-5 w-5 text-gray-400"
                  aria-hidden="true"
                />
                <span>Delete</span>
                <delete-confirmation
                  ref="deleteConfirmation"
                ></delete-confirmation>
              </button>
            </span>
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ArchiveIcon as ArchiveIconSolid } from '@heroicons/vue/solid'
import { XIcon } from '@heroicons/vue/solid'
import { ReplyIcon } from '@heroicons/vue/solid'
import { PopoverButton } from '@headlessui/vue'

import TagsPopover from './TagsPopover.vue'
import TagsDialog from './TagsDialog.vue'
import DeleteConfirmation from './DeleteConfirmation.vue'
import { useSelectionStore } from '../stores/selection'

import { computed, ref } from 'vue'

const tagsDialog = ref(null)

const store = useSelectionStore()

const numSelected = computed(() => store.selectedIds.size)
const clearSelected = () => store.clear()

function openTagsDialog() {
  tagsDialog.value.openModal()
}

const deleteConfirmation = ref(null)

function openDeleteConfirmation() {
  deleteConfirmation.value.openModal()
}
</script>

// src/app/(bookmarks)/top-toolbar.tsx
"use client"

import { selectedBookmarkIdsAtom } from "@/stores/selection"
import { Transition } from "@headlessui/react"
import { TagIcon, TrashIcon, XMarkIcon } from "@heroicons/react/20/solid"
import clsx from "clsx"
import { useAtom } from "jotai"
import { useResetAtom } from "jotai/utils"
import DeleteBookmarks from "./delete-bookmarks"
import EditTagsDialog from "./tags-dialog"
import TagsPopover from "./tags-popover"

export default function TopToolbar() {
  const [selectedBookmarkIds] = useAtom(selectedBookmarkIdsAtom)
  const clearSelectedIds = useResetAtom(selectedBookmarkIdsAtom)

  const numSelected = selectedBookmarkIds.size

  return (
    <Transition show={numSelected > 0}>
      <div
        className={clsx([
          // Base styles
          "flex h-16 mx-4 items-center justify-between bg-white sm:justify-start transition",
          // Closed styles
          "data-[closed]:opacity-0 data-[closed]:-translate-y-6",
          // Entering styles
          "data-[enter]:duration-200 data-[enter]:ease-out",
          // Leaving styles
          "data-[leave]:duration-150 data-[leave]:ease-in",
        ])}
      >
        <div className="flex items-center">
          <button
            type="button"
            className="inline-flex items-center rounded-full border border-transparent bg-transparent text-gray-600 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:p-2"
            onClick={clearSelectedIds}
          >
            <XMarkIcon className="h-5 w-5" aria-hidden="true" />
          </button>
          <div className="mx-4 tabular-nums">{numSelected} selected</div>
        </div>
        <div className="sm:px-6 lg:px-8">
          <div className="flex justify-between py-3">
            <div>
              <span className="relative z-0 inline-flex space-x-3 rounded-md">
                <span className="hidden sm:inline-flex sm:shadow-sm">
                  <TagsPopover
                    bookmarkId={Array.from(selectedBookmarkIds)}
                    className="relative -ml-px inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:border-blue-600 focus:outline-none focus:ring-1 focus:ring-blue-600"
                  >
                    <TagIcon
                      className="mr-2.5 h-5 w-5 text-gray-400"
                      aria-hidden="true"
                    />
                    <span>Edit</span>
                  </TagsPopover>
                </span>
                <span className="inline-flex sm:hidden">
                  <EditTagsDialog
                    bookmarkId={Array.from(selectedBookmarkIds)}
                    className="relative -ml-px inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:border-blue-600 focus:outline-none focus:ring-1 focus:ring-blue-600"
                  >
                    <TagIcon
                      className="mr-2.5 h-5 w-5 text-gray-400"
                      aria-hidden="true"
                    />
                    <span>Edit</span>
                  </EditTagsDialog>
                </span>
                <span className="inline-flex sm:shadow-sm">
                  <DeleteBookmarks
                    bookmarkId={Array.from(selectedBookmarkIds)}
                    className="relative -ml-px inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-900 hover:bg-gray-50 focus:z-10 focus:border-blue-600 focus:outline-none focus:ring-1 focus:ring-blue-600"
                  >
                    <TrashIcon
                      className="mr-2.5 h-5 w-5 text-gray-400"
                      aria-hidden="true"
                    />
                    <span>Delete</span>
                  </DeleteBookmarks>
                </span>
              </span>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  )
}
