// src/components/EditTags.vue
<template>
  <div class="divide-y divide-gray-200">
    <div class="flex flex-wrap gap-2 px-4 py-4 sm:px-6">
      <span v-if="tags.length === 0">No tags</span>
      <tag-button
        v-else
        v-for="tag in tags"
        :key="tag.name"
        :name="tag.name"
        :accented="tag.accented"
        :showRemove="true"
        :onClick="onRemove"
      >
      </tag-button>
    </div>
    <div class="px-4 py-5 sm:p-6">
      <div class="relative flex">
        <label for="add-tag" class="sr-only">Add tag</label>
        <input
          type="text"
          tabindex="-1"
          :placeholder="placeholder"
          class="block w-full rounded-md border-gray-300 bg-white shadow-sm placeholder:text-slate-400 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
        />
        <input
          type="text"
          v-model="newTag"
          autocomplete="off"
          name="add-tag"
          id="add-tag"
          class="absolute top-0 left-0 block w-full rounded-md border-gray-300 bg-transparent text-default shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
          @keyup.enter="onEnter"
          @keydown.tab.stop.prevent="onTab"
          ref="addTagInput"
        />
      </div>
    </div>
  </div>
</template>

<script>
import _ from 'lodash'
import TagButton from './TagButton.vue'
import { computed, ref } from 'vue'
import useBulkEditBookmarks from '../composables/useBulkEditBookmarks'
import useEditBookmark from '../composables/useEditBookmark'
import { lookup } from '../lib/typeahead'
import { useTags } from '../composables/useTags'
import { tagsWithAccentBit } from '../lib/tagsRow'
import { usePageStore } from '../stores/page'

const TYPEAHEAD_ACTIVATION_THRESHOLD = 1

export default {
  components: {
    TagButton,
  },
  props: {
    bookmarkId: String,
    bulk: Boolean,
    popup: Boolean,
  },
  mounted() {
    this.$refs.addTagInput.focus()
  },
  setup(props) {
    const newTag = ref('')

    const tagSuggestion = ref('')
    const { data } = useTags()
    const allTags = computed(() => data.value || [])

    const addTagInput = ref(null)

    const { tags, addTag, removeTag } = props.bulk
      ? useBulkEditBookmarks()
      : props.bookmarkId
      ? useEditBookmark(props.bookmarkId)
      : { tags: ref(null), addTag: () => {}, removeTag: () => {} }

    const displayTags = computed(() => {
      if (!tags.value) {
        return []
      }
      let pageTags = []
      if (!props.popup) {
        const pageStore = usePageStore()
        pageTags = pageStore.tags
      }
      return tagsWithAccentBit(tags.value, pageTags)
    })
    const placeholder = computed(() => {
      if (
        !newTag.value.length ||
        newTag.value.length < TYPEAHEAD_ACTIVATION_THRESHOLD
      ) {
        tagSuggestion.value = ''
        return ''
      }
      let candidates = lookup(allTags.value, newTag.value)
      // Remove existing tags from autocomplete candidates
      _.pullAll(candidates, tags.value)
      if (!candidates.length) {
        tagSuggestion.value = ''
        return ''
      }
      tagSuggestion.value = candidates[0]
      let suggestion = candidates[0].split('')
      let userInput = newTag.value.split('')
      userInput.forEach((letter, key) => {
        if (letter !== suggestion[key]) {
          suggestion[key] = letter
        }
      })
      return suggestion.join('')
    })
    function tryAddTag(tagName) {
      if (!tagName.trim()) {
        return
      }

      let cleanedTagName = tagName.trim().replace(/\s+/g, ' ')
      addTag(cleanedTagName)
      newTag.value = ''
    }
    const onEnter = () => tryAddTag(newTag.value)
    const onTab = () => {
      const tagToAdd = tagSuggestion.value.length
        ? tagSuggestion.value
        : newTag.value
      tryAddTag(tagToAdd)
    }
    return {
      newTag,
      addTagInput,
      placeholder,
      tags: displayTags,
      onEnter,
      onTab,
      onRemove: removeTag,
    }
  },
}
</script>

// src/components/edit-tags.tsx
import { useBookmarkTags } from "@/lib/queries"
import _ from "lodash"
import { useState } from "react"
import TagButton from "./tag-button"

type EditTagsProps = {
  bookmarkId: string | string[]
  pageTags?: string[]
}

const CASE_SENSITIVE_TAGS = false

function lookup(
  tags: Array<{ name: string; count: number }>,
  query: string
): string[] {
  const searchQuery = CASE_SENSITIVE_TAGS ? query : query.toLowerCase()

  let searchResults = []

  for (const { name: tag, count: freq } of tags) {
    const candidate = CASE_SENSITIVE_TAGS ? tag : tag.toLowerCase()
    if (candidate.startsWith(searchQuery)) {
      searchResults.push([tag, freq] as const)
    }
  }

  // Sort the search results by decreasing tag frequency
  searchResults.sort(([, freq1], [, freq2]) => {
    return -(freq1 - freq2)
  })

  return searchResults.map(([tag]) => tag)
}

function tagsWithAccentBit(allTags: string[], pageTags: string[]) {
  let result = pageTags
    .filter((t) => allTags.includes(t))
    .map((t) => ({ name: t, accented: true }))
  result = result.concat(
    allTags
      .filter((t) => !pageTags.includes(t))
      .map((t) => ({ name: t, accented: false }))
  )
  return result
}

export default function EditTags({ bookmarkId, pageTags }: EditTagsProps) {
  const bookmarkIds = Array.isArray(bookmarkId) ? bookmarkId : [bookmarkId]

  const [newTag, setNewTag] = useState("")

  let {
    tags: bookmarkTags,
    allTags,
    addTag,
    removeTag,
  } = useBookmarkTags(bookmarkIds)

  const tags = tagsWithAccentBit(bookmarkTags, pageTags ?? [])

  const handleAddTag = (tagName: string) => {
    setNewTag("")
    if (tagName) {
      addTag(tagName)
    }
  }

  let placeholder = ""
  let tagSuggestion = ""
  if (newTag && allTags) {
    let candidates = lookup(allTags, newTag)

    // Remove existing tags from autocomplete candidates
    _.pullAll(candidates, bookmarkTags)

    if (candidates.length) {
      tagSuggestion = candidates[0]
      let suggestion = tagSuggestion.split("")
      let userInput = newTag.split("")
      userInput.forEach((letter, key) => {
        if (letter !== suggestion[key]) {
          suggestion[key] = letter
        }
      })
      placeholder = suggestion.join("")
    }
  }

  return (
    <div className="overflow-hidden rounded-lg bg-white shadow-lg ring-1 ring-black ring-opacity-5">
      <div className="divide-y divide-gray-200">
        <div className="flex flex-wrap gap-2 px-4 py-4 sm:px-6">
          {tags.length === 0 && <span>No tags</span>}
          {tags.map((tag) => (
            <TagButton
              key={tag.name}
              name={tag.name}
              showRemove={true}
              accented={tag.accented}
              onClick={() => removeTag(tag.name)}
            />
          ))}
        </div>
        <div className="px-4 py-5 sm:p-6">
          <div className="relative flex">
            <label htmlFor="add-tag" className="sr-only">
              Add tag
            </label>
            <input
              type="text"
              tabIndex={-1}
              placeholder={placeholder}
              className="block w-full rounded-md border-gray-300 bg-white shadow-sm placeholder:text-slate-400 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
            />
            <input
              type="text"
              tabIndex={1}
              autoComplete="off"
              name="add-tag"
              id="add-tag"
              value={newTag}
              className="absolute top-0 left-0 block w-full rounded-md border-gray-300 bg-transparent text-default shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              onChange={(e) => setNewTag(e.target.value)}
              onKeyUp={(e) => {
                if (e.key === "Enter") {
                  let cleanedTagName = newTag.trim().replace(/\s+/g, " ")
                  handleAddTag(cleanedTagName)
                }
              }}
              onKeyDown={(e) => {
                if (e.key === "Tab") {
                  e.preventDefault()
                  const tagToAdd = tagSuggestion.length ? tagSuggestion : newTag
                  let cleanedTagName = tagToAdd.trim().replace(/\s+/g, " ")
                  handleAddTag(cleanedTagName)
                }
              }}
            />
          </div>
        </div>
      </div>
    </div>
  )
}
