// src/components/search-bar.tsx
"use client"

import { MagnifyingGlassIcon } from "@heroicons/react/20/solid"
import { useRouter, useSearchParams } from "next/navigation"
import { useEffect, useRef } from "react"
import { useDebouncedCallback } from "use-debounce"

export default function SearchBar() {
  const router = useRouter()
  let searchParams = useSearchParams()
  let query = searchParams.get("q") ?? ""
  const inputRef = useRef<HTMLInputElement>(null)

  const handleSearch = useDebouncedCallback((newQuery: string) => {
    const params = new URLSearchParams(searchParams.toString())

    if (!newQuery) {
      params.delete("cursor")
      params.delete("q")
      router.push(`/?${params.toString()}`)
      return
    }

    let isSearch = !!query
    params.delete("cursor")
    params.set("q", newQuery)
    const url = `/?${params.toString()}`
    if (isSearch) {
      router.replace(url)
    } else {
      router.push(url)
    }
  }, 300)

  useEffect(() => {
    if (query === "" && inputRef.current) {
      inputRef.current.value = ""
    }
  }, [query])

  return (
    <div className="flex flex-1 justify-center lg:justify-end">
      <div className="w-full px-2 lg:px-6">
        <label htmlFor="search" className="sr-only">
          Search bookmarks
        </label>
        <div className="text-black-200 relative h-[46px] focus-within:text-gray-400">
          <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
            <MagnifyingGlassIcon className="h-5 w-5" aria-hidden="true" />
          </div>
          <input
            type="text"
            defaultValue={query}
            placeholder="Search bookmarks"
            autoComplete="off"
            spellCheck="false"
            id="search"
            name="search"
            className="text-black-100 placeholder-black-200 block h-full w-full rounded-md border border-transparent bg-gray-400 bg-opacity-25 py-2 pl-10 pr-3 leading-5 focus:bg-white focus:text-gray-900 focus:placeholder-gray-400 focus:outline-none focus:ring-1 sm:text-sm"
            onChange={(e) => handleSearch(e.target.value)}
            ref={inputRef}
          />
        </div>
      </div>
    </div>
  )
}

// src/components/SearchBar.vue
<template>
  <div>
    <input type="text" placeholder="Search bookmarks" autocomplete="off" spellcheck="false"
           v-model="query" @keyup="doSearch"
           class="focus:outline-none text-sm text-muted border border-transparent focus:bg-default focus:border-primary rounded bg-grey-100 py-2 pr-4 pl-10 block w-full appearance-none leading-normal">
    <div class="absolute pin-y pin-l pl-3 flex items-center" v-if="query">
      <svg class="fill-current text-muted w-5 h-5 cursor-pointer" @click="clearSearch" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
        <path d="M50,14c-19.9,0-36,16.1-36,36s16.1,36,36,36s36-16.1,36-36S69.9,14,50,14z M62.4,59.6c0.8,0.8,0.8,2,0,2.8   C62,62.8,61.5,63,61,63s-1-0.2-1.4-0.6L50,52.8l-9.6,9.6C40,62.8,39.5,63,39,63s-1-0.2-1.4-0.6c-0.8-0.8-0.8-2,0-2.8l9.6-9.6   l-9.6-9.6c-0.8-0.8-0.8-2,0-2.8c0.8-0.8,2-0.8,2.8,0l9.6,9.6l9.6-9.6c0.8-0.8,2-0.8,2.8,0c0.8,0.8,0.8,2,0,2.8L52.8,50L62.4,59.6z"></path>
      </svg>
    </div>
    <div class="absolute pin-y pin-l pl-3 flex items-center" v-else>
      <svg class="fill-current pointer-events-none text-muted w-4 h-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
      </svg>
    </div>
  </div>
</template>

<script>
  import _ from 'lodash'

  export default {
    name: 'search-bar',

    data: function () {
      return {
        query: ''
      }
    },

    methods: {
      doSearch: _.debounce(function () {
        let query = this.query.trim()
        if (query === '') {
          this.$router.push('/')
        } else {
          this.$router.push(`/q/${query}`)
        }
      }, 300),
      clearSearch: function () {
        this.query = ''
        this.$router.push('/')
      }
    },

    watch: {
      '$route' ({ name }) {
        if (name !== 'search') {
          // Clear search bar when we browse away from search results
          this.query = ''
        }
      }
    },
  }
</script>
