// src/app/(bookmarks)/tags-popover.tsx
import EditTags from "@/components/edit-tags"
import { Popover, PopoverButton, PopoverPanel } from "@headlessui/react"
import { useSearchParams } from "next/navigation"

export default function TagsPopover({
  bookmarkId,
  className,
  children,
}: {
  bookmarkId: string | string[]
  className?: string
  children: React.ReactNode
}) {
  const searchParams = useSearchParams()
  const pageTags = searchParams.getAll("name")

  return (
    <Popover className="relative">
      <PopoverButton type="button" className={className}>
        {children}
      </PopoverButton>
      <PopoverPanel
        focus
        className="absolute left-0 z-50 mt-3 w-screen max-w-xs px-2 sm:px-0"
      >
        <EditTags bookmarkId={bookmarkId} pageTags={pageTags} />
      </PopoverPanel>
    </Popover>
  )
}

// src/components/TagsPopover.vue
<template>
  <Popover class="relative">
    <slot></slot>
    <transition
      enter-active-class="transition ease-out duration-200"
      enter-from-class="opacity-0 translate-y-1"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition ease-in duration-150"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 translate-y-1"
    >
      <PopoverPanel
        class="absolute z-50 left-0 mt-3 px-2 w-screen max-w-xs sm:px-0"
      >
        <edit-tags></edit-tags>
      </PopoverPanel>
    </transition>
  </Popover>
</template>

<script setup>
import { Popover, PopoverPanel } from '@headlessui/vue'
import EditTags from './EditTags.vue'
</script>
